import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:villavibe/features/properties/domain/models/property.dart';


final List<Property> seedProperties = [
  Property(
    id: '',
    hostId: 'seed_host_1',
    name: 'Bamboo Eco-Sanctuary',
    description: 'Immerse yourself in nature in this stunning bamboo villa. Designed for sustainability and luxury, this open-air sanctuary offers breathtaking views of the jungle valley.',
    pricePerNight: 2500000,
    address: 'Ubud, Bali',
    city: 'Ubud',
    specs: PropertySpecs(bedrooms: 2, bathrooms: 2, maxGuests: 4),
    amenities: ['Wifi', 'Pool', 'AC', 'Kitchen', 'Parking'],
    images: [
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1598928636135-d146006ff4be?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    ],
    rating: 4.9,
    hostName: 'Wayan',
    hostAvatar: 'https://i.pravatar.cc/150?u=wayan',
    hostYearsHosting: 5,
    reviewsCount: 128,
    categoryId: 'villa',
    architectureStyle: 'Bamboo',
    landSize: 500,
    vibe: 'Zen',
    bedroomNames: ['Master Suite', 'River View Room'],
    setting: 'Jungle Edge',
    privacyLevel: 'Secluded',
    staffServices: ['Daily Housekeeping', 'Private Chef'],
    outdoorAmenities: ['Infinity Pool', 'Yoga Deck'],
    location: const GeoPoint(-8.5069, 115.2625),
  ),
  Property(
    id: '',
    hostId: 'seed_host_2',
    name: 'Modern Minimalist Beach House',
    description: 'Sleek lines and ocean views define this modern masterpiece. Just steps from the sand, enjoy indoor-outdoor living at its finest.',
    pricePerNight: 5500000,
    address: 'Canggu, Bali',
    city: 'Canggu',
    specs: PropertySpecs(bedrooms: 3, bathrooms: 3, maxGuests: 6),
    amenities: ['Wifi', 'Pool', 'AC', 'Kitchen', 'Gym'],
    images: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    ],
    rating: 4.8,
    hostName: 'Sarah',
    hostAvatar: 'https://i.pravatar.cc/150?u=sarah',
    hostYearsHosting: 3,
    reviewsCount: 85,
    categoryId: 'villa',
    architectureStyle: 'Modern',
    landSize: 300,
    vibe: 'Party',
    bedroomNames: ['Ocean Master', 'Guest Room 1', 'Guest Room 2'],
    setting: 'Beachfront',
    privacyLevel: 'Private',
    staffServices: ['Butler', 'Security'],
    outdoorAmenities: ['Rooftop Bar', 'BBQ Area'],
    location: const GeoPoint(-8.6478, 115.1385),
  ),
  Property(
    id: '',
    hostId: 'seed_host_3',
    name: 'Traditional Joglo Estate',
    description: 'Experience authentic Balinese royalty in this restored Joglo estate. Antique teak wood, sprawling gardens, and a massive pool await.',
    pricePerNight: 3200000,
    address: 'Seminyak, Bali',
    city: 'Seminyak',
    specs: PropertySpecs(bedrooms: 4, bathrooms: 4, maxGuests: 8),
    amenities: ['Wifi', 'Pool', 'AC', 'Kitchen', 'Garden'],
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b91d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    ],
    rating: 4.95,
    hostName: 'Ketut',
    hostAvatar: 'https://i.pravatar.cc/150?u=ketut',
    hostYearsHosting: 10,
    reviewsCount: 210,
    categoryId: 'villa',
    architectureStyle: 'Joglo',
    landSize: 1200,
    vibe: 'Family',
    bedroomNames: ['Royal Joglo', 'Garden Suite', 'Poolside 1', 'Poolside 2'],
    setting: 'Garden Estate',
    privacyLevel: 'Walled',
    staffServices: ['Full Staff', 'Driver'],
    outdoorAmenities: ['Large Pool', 'Gazebo', 'Fish Pond'],
    location: const GeoPoint(-8.6898, 115.1686),
  ),
   Property(
    id: '',
    hostId: 'seed_host_4',
    name: 'Cliffside Industrial Loft',
    description: 'Raw concrete meets luxury in this industrial loft perched on a cliff. Unobstructed ocean views and a private plunge pool.',
    pricePerNight: 4100000,
    address: 'Uluwatu, Bali',
    city: 'Uluwatu',
    specs: PropertySpecs(bedrooms: 1, bathrooms: 1, maxGuests: 2),
    amenities: ['Wifi', 'Pool', 'AC', 'Kitchen', 'Workplace'],
    images: [
      'https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1600596542815-22b5c1275efb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    ],
    rating: 4.7,
    hostName: 'Alex',
    hostAvatar: 'https://i.pravatar.cc/150?u=alex',
    hostYearsHosting: 2,
    reviewsCount: 45,
    categoryId: 'villa',
    architectureStyle: 'Industrial',
    landSize: 150,
    vibe: 'Romantic',
    bedroomNames: ['Loft Bedroom'],
    setting: 'Cliffside',
    privacyLevel: 'Private',
    staffServices: ['Breakfast Included'],
    outdoorAmenities: ['Plunge Pool', 'Sunset Deck'],
    location: const GeoPoint(-8.8149, 115.0884),
  ),
  Property(
    id: '',
    hostId: 'seed_host_5',
    name: 'Tropical Jungle Hideaway',
    description: 'A lush escape surrounded by palm trees. This tropical villa features an open living area and a refreshing natural stone pool.',
    pricePerNight: 1800000,
    address: 'Pererenan, Bali',
    city: 'Pererenan',
    specs: PropertySpecs(bedrooms: 2, bathrooms: 2, maxGuests: 4),
    amenities: ['Wifi', 'Pool', 'AC', 'Kitchen', 'Parking'],
    images: [
      'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80',
    ],
    rating: 4.85,
    hostName: 'Made',
    hostAvatar: 'https://i.pravatar.cc/150?u=made',
    hostYearsHosting: 7,
    reviewsCount: 92,
    categoryId: 'villa',
    architectureStyle: 'Tropical',
    landSize: 400,
    vibe: 'Work',
    bedroomNames: ['Palm Room', 'Garden Room'],
    setting: 'Rice Field View',
    privacyLevel: 'Quiet',
    staffServices: ['Housekeeping'],
    outdoorAmenities: ['Pool', 'Hammock'],
    location: const GeoPoint(-8.6500, 115.1200),
  ),
];
